/*
	Name: autoComplete
	Author: Raymond Camden & Andy Matthews
	Contributors: Jim Pease (@jmpease)
	Website: http://raymondcamden.com/
			 http://andyMatthews.net
	Packed With: http://jsutility.pjoneil.net/
	Version: 1.3
 */
(function(a){"use strict";var b={method:"GET",icon:"arrow-r",cancelRequests:false,target:a(),source:null,callback:null,link:null,minLength:0,transition:"fade"},c={},d=function(b,c,d){var f=[];if(c){a.each(c,function(b,c){if(a.isPlainObject(c)){f.push("<li data-icon="+d.icon+'><a href="'+d.link+encodeURIComponent(c.value)+'" data-transition="'+d.transition+'">'+c.label+"</a></li>")}else{f.push("<li data-icon="+d.icon+'><a href="'+d.link+encodeURIComponent(c)+'" data-transition="'+d.transition+'">'+c+"</a></li>")}})}a(d.target).html(f.join("")).listview("refresh");if(d.callback!=null&&a.isFunction(d.callback)){e(d)}if(f.length>0){b.trigger("targetUpdated.autocomplete")}else{b.trigger("targetCleared.autocomplete")}},e=function(b){a("li a",a(b.target)).bind("click.autocomplete",function(a){a.stopPropagation();a.preventDefault();b.callback(a)})},f=function(a,b){b.html("").listview("refresh").closest("fieldset").removeClass("ui-search-active");a.trigger("targetCleared.autocomplete")},g=function(b){var e=a(this),g=e.attr("id"),h,i,j=e.jqmData("autocomplete");if(j){h=e.val();if(h.length<j.minLength){f(e,a(j.target))}else{if(a.isArray(j.source)){i=j.source.sort().filter(function(b){var c,d=new RegExp("^"+h,"i");if(a.isPlainObject(b)){c=b.label}else{c=b}return d.test(c)});d(e,i,j)}else{a.ajax({type:j.method,url:j.source,data:{term:h},beforeSend:function(a){if(j.cancelRequests){if(c[g]){c[g].abort()}else{j.target.html('<li data-icon="none"><a href="#">Searching...</a></li>').listview("refresh");j.target.closest("fieldset").addClass("ui-search-active")}c[g]=a}},success:function(a){d(e,a,j)},complete:function(a,b){if(j.cancelRequests){c[g]=null}},dataType:"json"})}}}},h={init:function(c){this.jqmData("autocomplete",a.extend({},b,c));return this.unbind("keyup.autocomplete").bind("keyup.autocomplete",g)},update:function(b){var c=this.jqmData("autocomplete");if(c){this.jqmData("autocomplete",a.extend(c,b))}return this},clear:function(){var b=this.jqmData("autocomplete");if(b){f(this,a(b.target))}return this},destroy:function(){var b=this.jqmData("autocomplete");if(b){f(this,a(b.target));this.jqmRemoveData("autocomplete");this.unbind(".autocomplete")}return this}};a.fn.autocomplete=function(a){if(h[a]){return h[a].apply(this,Array.prototype.slice.call(arguments,1))}else if(typeof a==="object"||!a){return h.init.apply(this,arguments)}}})(jQuery)